### ISSUE TITLE
Refresh from upstream?

### ISSUE THREAD

**Issue by vspinu** [dselivanov/r-sparsepp#3]
Would you please pull from upstream and re-release to CRAN? There has been an important fix for int64 keys which has a ridiculous 10-100x performance benefit for my use case.

**Comment by dselivanov** [comment]
Could you please point to the commit/tag in upstream?

**Comment by vspinu** [comment]
Sure. This is the relevant commit greg7mdp/sparsepp@27c61e7b5908 and is part of v1.2 and v1.21 now. I tested it locally and that new hash makes a huge difference.

**Comment by dselivanov** [comment]
Thanks, I will try to update on weekend

**Comment by dselivanov** [comment]
on the way to cran

**Comment by vspinu** [comment]
Thanks!

**Comment by vspinu** [comment]
There is a new problem. Gcc 8+ throws a [warning](https://win-builder.r-project.org/incoming_pretest/mlvocab_0.1_20180917_195404/Debian/00check.log) which was just fixed in the [upstream](https://github.com/greg7mdp/sparsepp/issues/66). The warning is deemed important and R packages fail the pre-test because of that.

**Comment by dselivanov** [comment]
Send a PR please. Currently have 0 spare time to update it.

вт, 18 сент. 2018 г., 1:03 Vitalie Spinu <notifications@github.com>:

**Comment by vspinu** [comment]
Do you do any special post processing that I should know about?

**Comment by dselivanov** [comment]
Nothing special - see previous update. I think current update will be
similar.

вт, 18 сент. 2018 г., 22:08 Vitalie Spinu <notifications@github.com>:

**Comment by vspinu** [comment]
Could you merge the upstream into your sparsepp branch? 

I think this 2 repo solution is not ideal if you are willing for external contributors on such tasks. Too much trouble for both of us. 

How about keeping a patch inside the repo and having a script which would pull the upstream, apply the patch, pick the version from the upstream, build the package and run R check all in one blow? On your side you would just need to run the script and and submit to cran every time an update happens.

**Comment by vspinu** [comment]
Actually the author of sparsepp might be willing to replace those exits and fprintfs in the main repo (greg7mdp/sparsepp#71).

**Comment by dselivanov** [comment]
Nice. I will update then.

ср, 19 сент. 2018 г., 19:09 Vitalie Spinu <notifications@github.com>:
